--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create input_account
local input_account = ccui.TextField:create()
input_account:ignoreContentAdaptWithSize(false)
tolua.cast(input_account:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
input_account:setFontSize(30)
input_account:setPlaceHolder("请输入账号")
input_account:setString([[]])
input_account:setMaxLength(10)
input_account:setLayoutComponentEnabled(true)
input_account:setName("input_account")
input_account:setTag(3)
input_account:setCascadeColorEnabled(true)
input_account:setCascadeOpacityEnabled(true)
input_account:setAnchorPoint(0.0000, 0.5000)
input_account:setPosition(577.0966, 446.9615)
layout = ccui.LayoutComponent:bindLayoutComponent(input_account)
layout:setPositionPercentX(0.4509)
layout:setPositionPercentY(0.6208)
layout:setPercentWidth(0.1563)
layout:setPercentHeight(0.0431)
layout:setSize({width = 200.0000, height = 31.0000})
layout:setHorizontalEdge(3)
layout:setLeftMargin(577.0966)
layout:setRightMargin(502.9034)
layout:setTopMargin(257.5385)
layout:setBottomMargin(431.4615)
Layer:addChild(input_account)

--Create label_account
local label_account = ccui.Text:create()
label_account:ignoreContentAdaptWithSize(true)
label_account:setTextAreaSize({width = 0, height = 0})
label_account:setFontName("fonts/mnjcy.ttf")
label_account:setFontSize(30)
label_account:setString([[账号:]])
label_account:setLayoutComponentEnabled(true)
label_account:setName("label_account")
label_account:setTag(4)
label_account:setCascadeColorEnabled(true)
label_account:setCascadeOpacityEnabled(true)
label_account:setPosition(-45.7885, 13.9600)
layout = ccui.LayoutComponent:bindLayoutComponent(label_account)
layout:setPositionPercentX(-0.2289)
layout:setPositionPercentY(0.4503)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(1.0968)
layout:setSize({width = 70.0000, height = 34.0000})
layout:setLeftMargin(-80.7885)
layout:setRightMargin(210.7885)
layout:setTopMargin(0.0400)
layout:setBottomMargin(-3.0400)
input_account:addChild(label_account)

--Create input_password
local input_password = ccui.TextField:create()
input_password:ignoreContentAdaptWithSize(false)
tolua.cast(input_password:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
input_password:setFontSize(30)
input_password:setPlaceHolder("请输入密码")
input_password:setString([[]])
input_password:setMaxLength(10)
input_password:setPasswordEnabled(true)
input_password:setLayoutComponentEnabled(true)
input_password:setName("input_password")
input_password:setTag(5)
input_password:setCascadeColorEnabled(true)
input_password:setCascadeOpacityEnabled(true)
input_password:setAnchorPoint(0.0000, 0.5000)
input_password:setPosition(578.2674, 390.3064)
layout = ccui.LayoutComponent:bindLayoutComponent(input_password)
layout:setPositionPercentX(0.4518)
layout:setPositionPercentY(0.5421)
layout:setPercentWidth(0.1563)
layout:setPercentHeight(0.0431)
layout:setSize({width = 200.0000, height = 31.0000})
layout:setHorizontalEdge(3)
layout:setLeftMargin(578.2674)
layout:setRightMargin(501.7326)
layout:setTopMargin(314.1936)
layout:setBottomMargin(374.8064)
Layer:addChild(input_password)

--Create label_password
local label_password = ccui.Text:create()
label_password:ignoreContentAdaptWithSize(true)
label_password:setTextAreaSize({width = 0, height = 0})
label_password:setFontName("fonts/mnjcy.ttf")
label_password:setFontSize(30)
label_password:setString([[密码:]])
label_password:setLayoutComponentEnabled(true)
label_password:setName("label_password")
label_password:setTag(6)
label_password:setCascadeColorEnabled(true)
label_password:setCascadeOpacityEnabled(true)
label_password:setPosition(-48.8460, 16.6600)
layout = ccui.LayoutComponent:bindLayoutComponent(label_password)
layout:setPositionPercentX(-0.2442)
layout:setPositionPercentY(0.5374)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(1.0968)
layout:setSize({width = 70.0000, height = 34.0000})
layout:setLeftMargin(-83.8460)
layout:setRightMargin(213.8459)
layout:setTopMargin(-2.6600)
layout:setBottomMargin(-0.3400)
input_password:addChild(label_password)

--Create btn_login
local btn_login = ccui.Button:create()
btn_login:ignoreContentAdaptWithSize(false)
btn_login:loadTextureNormal("res/widget/btn_cheng.png",0)
btn_login:loadTexturePressed("res/widget/btn_cheng.png",0)
btn_login:loadTextureDisabled("Default/Button_Disable.png",0)
btn_login:setTitleFontSize(14)
btn_login:setTitleColor({r = 65, g = 65, b = 70})
btn_login:setScale9Enabled(true)
btn_login:setCapInsets({x = 15, y = 11, width = 203, height = 62})
btn_login:setLayoutComponentEnabled(true)
btn_login:setName("btn_login")
btn_login:setTag(7)
btn_login:setCascadeColorEnabled(true)
btn_login:setCascadeOpacityEnabled(true)
btn_login:setPosition(640.0000, 183.2100)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_login)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2545)
layout:setPercentWidth(0.1820)
layout:setPercentHeight(0.1167)
layout:setSize({width = 233.0000, height = 84.0000})
layout:setHorizontalEdge(3)
layout:setLeftMargin(523.5000)
layout:setRightMargin(523.5000)
layout:setTopMargin(494.7900)
layout:setBottomMargin(141.2100)
Layer:addChild(btn_login)

--Create Text_3
local Text_3 = ccui.Text:create()
Text_3:ignoreContentAdaptWithSize(true)
Text_3:setTextAreaSize({width = 0, height = 0})
Text_3:setFontName("fonts/mnjcy.ttf")
Text_3:setFontSize(36)
Text_3:setString([[登     录]])
Text_3:setLayoutComponentEnabled(true)
Text_3:setName("Text_3")
Text_3:setTag(8)
Text_3:setCascadeColorEnabled(true)
Text_3:setCascadeOpacityEnabled(true)
Text_3:setPosition(113.1469, 42.6137)
Text_3:setTextColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_3)
layout:setPositionPercentX(0.4856)
layout:setPositionPercentY(0.5073)
layout:setPercentWidth(0.5322)
layout:setPercentHeight(0.4881)
layout:setSize({width = 124.0000, height = 41.0000})
layout:setLeftMargin(51.1469)
layout:setRightMargin(57.8532)
layout:setTopMargin(20.8863)
layout:setBottomMargin(22.1137)
btn_login:addChild(Text_3)

--Create btn_register
local btn_register = ccui.Button:create()
btn_register:ignoreContentAdaptWithSize(false)
btn_register:loadTextureNormal("res/widget/btn_lan.png",0)
btn_register:loadTexturePressed("res/widget/btn_lan.png",0)
btn_register:loadTextureDisabled("Default/Button_Disable.png",0)
btn_register:setTitleFontSize(14)
btn_register:setTitleColor({r = 65, g = 65, b = 70})
btn_register:setScale9Enabled(true)
btn_register:setCapInsets({x = 15, y = 11, width = 203, height = 62})
btn_register:setLayoutComponentEnabled(true)
btn_register:setName("btn_register")
btn_register:setTag(20)
btn_register:setCascadeColorEnabled(true)
btn_register:setCascadeOpacityEnabled(true)
btn_register:setPosition(640.0005, 94.3669)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_register)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1311)
layout:setPercentWidth(0.1820)
layout:setPercentHeight(0.1167)
layout:setSize({width = 233.0000, height = 84.0000})
layout:setHorizontalEdge(3)
layout:setLeftMargin(523.5005)
layout:setRightMargin(523.4995)
layout:setTopMargin(583.6331)
layout:setBottomMargin(52.3669)
Layer:addChild(btn_register)

--Create Text_3
local Text_3 = ccui.Text:create()
Text_3:ignoreContentAdaptWithSize(true)
Text_3:setTextAreaSize({width = 0, height = 0})
Text_3:setFontName("fonts/mnjcy.ttf")
Text_3:setFontSize(36)
Text_3:setString([[注     册 ]])
Text_3:setLayoutComponentEnabled(true)
Text_3:setName("Text_3")
Text_3:setTag(21)
Text_3:setCascadeColorEnabled(true)
Text_3:setCascadeOpacityEnabled(true)
Text_3:setPosition(113.1469, 42.6137)
Text_3:setTextColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_3)
layout:setPositionPercentX(0.4856)
layout:setPositionPercentY(0.5073)
layout:setPercentWidth(0.5322)
layout:setPercentHeight(0.4881)
layout:setSize({width = 124.0000, height = 41.0000})
layout:setLeftMargin(51.1469)
layout:setRightMargin(57.8532)
layout:setTopMargin(20.8863)
layout:setBottomMargin(22.1137)
btn_register:addChild(Text_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

