--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create bg
local bg = ccui.Layout:create()
bg:ignoreContentAdaptWithSize(false)
bg:setClippingEnabled(false)
bg:setBackGroundColorType(1)
bg:setBackGroundColor({r = 80, g = 30, b = 30})
bg:setTouchEnabled(true);
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(30)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setAnchorPoint(0.0000, 1.0000)
if callBackProvider~=nil then
      bg:addClickEventListener(callBackProvider("player_item.lua", bg, "hello"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setSize({width = 250.0000, height = 100.0000})
layout:setRightMargin(-250.0000)
layout:setBottomMargin(-100.0000)
Node:addChild(bg)

--Create ownerFlag
local ownerFlag = ccui.ImageView:create()
ownerFlag:ignoreContentAdaptWithSize(false)
ownerFlag:loadTexture("res/ownerflag.png",0)
ownerFlag:setLayoutComponentEnabled(true)
ownerFlag:setName("ownerFlag")
ownerFlag:setTag(77)
ownerFlag:setCascadeColorEnabled(true)
ownerFlag:setCascadeOpacityEnabled(true)
ownerFlag:setPosition(22.4841, 114.7152)
ownerFlag:setScaleX(0.7000)
ownerFlag:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(ownerFlag)
layout:setPositionPercentX(0.0899)
layout:setPositionPercentY(1.1472)
layout:setPercentWidth(0.4480)
layout:setPercentHeight(0.9700)
layout:setSize({width = 112.0000, height = 97.0000})
layout:setLeftMargin(-33.5159)
layout:setRightMargin(171.5159)
layout:setTopMargin(-63.2152)
layout:setBottomMargin(66.2152)
bg:addChild(ownerFlag)

--Create head
local head = ccui.ImageView:create()
head:ignoreContentAdaptWithSize(false)
head:loadTexture("res/boy.jpg",0)
head:setLayoutComponentEnabled(true)
head:setName("head")
head:setTag(31)
head:setCascadeColorEnabled(true)
head:setCascadeOpacityEnabled(true)
head:setPosition(50.4385, 50.3131)
head:setScaleX(0.3000)
head:setScaleY(0.3000)
layout = ccui.LayoutComponent:bindLayoutComponent(head)
layout:setPositionPercentX(0.2018)
layout:setPositionPercentY(0.5031)
layout:setPercentWidth(1.2000)
layout:setPercentHeight(3.0000)
layout:setSize({width = 300.0000, height = 300.0000})
layout:setLeftMargin(-99.5615)
layout:setRightMargin(49.5615)
layout:setTopMargin(-100.3131)
layout:setBottomMargin(-99.6869)
bg:addChild(head)

--Create winning
local winning = ccui.Text:create()
winning:ignoreContentAdaptWithSize(true)
winning:setTextAreaSize({width = 0, height = 0})
winning:setFontName("fonts/mnjcy.ttf")
winning:setFontSize(20)
winning:setString([[胜率:%0 局数:0]])
winning:setLayoutComponentEnabled(true)
winning:setName("winning")
winning:setTag(32)
winning:setCascadeColorEnabled(true)
winning:setCascadeOpacityEnabled(true)
winning:setAnchorPoint(0.0000, 0.5000)
winning:setPosition(103.0003, 26.1199)
layout = ccui.LayoutComponent:bindLayoutComponent(winning)
layout:setPositionPercentX(0.4120)
layout:setPositionPercentY(0.2612)
layout:setPercentWidth(0.5400)
layout:setPercentHeight(0.2300)
layout:setSize({width = 135.0000, height = 23.0000})
layout:setLeftMargin(103.0003)
layout:setRightMargin(11.9997)
layout:setTopMargin(62.3801)
layout:setBottomMargin(14.6199)
bg:addChild(winning)

--Create name
local name = ccui.Text:create()
name:ignoreContentAdaptWithSize(false)
name:setFontSize(24)
name:setString([[阳光灿烂猪]])
name:setLayoutComponentEnabled(true)
name:setName("name")
name:setTag(33)
name:setCascadeColorEnabled(true)
name:setCascadeOpacityEnabled(true)
name:setAnchorPoint(0.0000, 0.5000)
name:setPosition(103.0004, 73.1241)
layout = ccui.LayoutComponent:bindLayoutComponent(name)
layout:setPositionPercentX(0.4120)
layout:setPositionPercentY(0.7312)
layout:setPercentWidth(0.5760)
layout:setPercentHeight(0.2400)
layout:setSize({width = 144.0000, height = 24.0000})
layout:setLeftMargin(103.0004)
layout:setRightMargin(2.9996)
layout:setTopMargin(14.8759)
layout:setBottomMargin(61.1241)
bg:addChild(name)

--Create btn_changeDesk
local btn_changeDesk = ccui.Button:create()
btn_changeDesk:ignoreContentAdaptWithSize(false)
btn_changeDesk:loadTextureNormal("res/btn_xing.png",0)
btn_changeDesk:loadTexturePressed("res/btn_xing.png",0)
btn_changeDesk:loadTextureDisabled("Default/Button_Disable.png",0)
btn_changeDesk:setTitleFontSize(14)
btn_changeDesk:setTitleColor({r = 65, g = 65, b = 70})
btn_changeDesk:setScale9Enabled(true)
btn_changeDesk:setCapInsets({x = 15, y = 11, width = 26, height = 30})
btn_changeDesk:setLayoutComponentEnabled(true)
btn_changeDesk:setName("btn_changeDesk")
btn_changeDesk:setTag(94)
btn_changeDesk:setCascadeColorEnabled(true)
btn_changeDesk:setCascadeOpacityEnabled(true)
btn_changeDesk:setPosition(132.0000, -48.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_changeDesk)
layout:setSize({width = 56.0000, height = 52.0000})
layout:setLeftMargin(104.0000)
layout:setRightMargin(-160.0000)
layout:setTopMargin(22.0000)
layout:setBottomMargin(-74.0000)
Node:addChild(btn_changeDesk)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

