--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create bg
local bg = ccui.Layout:create()
bg:ignoreContentAdaptWithSize(false)
bg:setClippingEnabled(false)
bg:setBackGroundColorType(1)
bg:setBackGroundColor({r = 80, g = 30, b = 30})
bg:setTouchEnabled(true);
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(32)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setAnchorPoint(0.0000, 1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setSize({width = 250.0000, height = 100.0000})
layout:setRightMargin(-250.0000)
layout:setBottomMargin(-100.0000)
Node:addChild(bg)

--Create head
local head = ccui.ImageView:create()
head:ignoreContentAdaptWithSize(false)
head:loadTexture("res/boy.jpg",0)
head:setLayoutComponentEnabled(true)
head:setName("head")
head:setTag(33)
head:setCascadeColorEnabled(true)
head:setCascadeOpacityEnabled(true)
head:setPosition(50.4385, 50.3131)
head:setScaleX(0.3000)
head:setScaleY(0.3000)
layout = ccui.LayoutComponent:bindLayoutComponent(head)
layout:setPositionPercentX(0.2018)
layout:setPositionPercentY(0.5031)
layout:setPercentWidth(1.2000)
layout:setPercentHeight(3.0000)
layout:setSize({width = 300.0000, height = 300.0000})
layout:setLeftMargin(-99.5615)
layout:setRightMargin(49.5615)
layout:setTopMargin(-100.3131)
layout:setBottomMargin(-99.6869)
bg:addChild(head)

--Create num
local num = ccui.Text:create()
num:ignoreContentAdaptWithSize(true)
num:setTextAreaSize({width = 0, height = 0})
num:setFontName("fonts/mnjcy.ttf")
num:setFontSize(30)
num:setString([[4/67]])
num:setLayoutComponentEnabled(true)
num:setName("num")
num:setTag(37)
num:setCascadeColorEnabled(true)
num:setCascadeOpacityEnabled(true)
num:setAnchorPoint(0.0000, 0.5000)
num:setPosition(103.0003, 26.1199)
layout = ccui.LayoutComponent:bindLayoutComponent(num)
layout:setPositionPercentX(0.4120)
layout:setPositionPercentY(0.2612)
layout:setPercentWidth(0.2600)
layout:setPercentHeight(0.3400)
layout:setSize({width = 65.0000, height = 34.0000})
layout:setLeftMargin(103.0003)
layout:setRightMargin(81.9997)
layout:setTopMargin(56.8801)
layout:setBottomMargin(9.1199)
bg:addChild(num)

--Create name
local name = ccui.Text:create()
name:ignoreContentAdaptWithSize(false)
name:setFontSize(24)
name:setString([[阳光灿烂猪]])
name:setLayoutComponentEnabled(true)
name:setName("name")
name:setTag(38)
name:setCascadeColorEnabled(true)
name:setCascadeOpacityEnabled(true)
name:setAnchorPoint(0.0000, 0.5000)
name:setPosition(103.0004, 73.1241)
layout = ccui.LayoutComponent:bindLayoutComponent(name)
layout:setPositionPercentX(0.4120)
layout:setPositionPercentY(0.7312)
layout:setPercentWidth(0.5760)
layout:setPercentHeight(0.2400)
layout:setSize({width = 144.0000, height = 24.0000})
layout:setLeftMargin(103.0004)
layout:setRightMargin(2.9996)
layout:setTopMargin(14.8759)
layout:setBottomMargin(61.1241)
bg:addChild(name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

